window.PORTFOLIO_PROJECTS = [
  { repo: "Meshtastic-Simulator", title: "Meshtastic-Simulator", iconClass: "devicon-python-plain card-icon", description: "A Python-based simulation tool for the Meshtastic mesh radio network.", href: "https://github.com/karelseaat/Meshtastic-Simulator" },
  { repo: "androidtosvg", title: "Binary Vector Graphics - Logo Design", iconClass: "devicon-android-plain card-icon", description: "This repository contains the source files for a vector graphics logo design created using Android's `<Vector>` library and Kotlin programming language. The logo is designed in two colors: dark red ...", href: "https://github.com/karelseaat/androidtosvg" },
  { repo: "api-app", title: "E-Commerce API", iconClass: "devicon-laravel-original card-icon", description: "A modern Laravel API application for managing products and orders. Built with Laravel 12, this API provides RESTful endpoints for e-commerce operations.", href: "https://github.com/karelseaat/api-app" },
  { repo: "apipython", title: "Python CLI API Tester", iconClass: "devicon-python-plain card-icon", description: "A simple, command-line API testing tool that allows you to define and run HTTP requests against different environments using a straightforward TOML configuration file.", href: "https://github.com/karelseaat/apipython" },
  { repo: "camsimulator", title: "GrblSimulator - A Graphical Interface for GRBL Simulation", iconClass: "devicon-python-plain card-icon", description: "GrblSimulator is a user-friendly graphical interface designed to simulate and visualize the operation of GRBL, an open-source CNC machine controller. The application allows users to manipulate the ...", href: "https://github.com/karelseaat/camsimulator" },
  { repo: "collectplayemails", title: "Project Title: My Application Management System (MAMS)", iconClass: "devicon-python-plain card-icon", description: "A comprehensive and flexible application management system for efficiently handling diverse applications, their metadata, and user interactions. MAMS is built using Python and SQLAlchemy, ensuring ...", href: "https://github.com/karelseaat/collectplayemails" },
  { repo: "datapanic", title: "Project Overview", iconClass: "devicon-cplusplus-plain card-icon", description: "This project is a collection of C++ classes for game development, focusing on essential components such as `Timer`, `Vector2D`, and `Animation`. These classes are designed to facilitate the creatio...", href: "https://github.com/karelseaat/datapanic" },
  { repo: "dataset_alter_tools", title: "dataset_alter_tools", iconClass: "devicon-python-plain card-icon", description: "A practical Python toolset for modifying and altering datasets, aimed at simplifying your machine learning workflow. This repository encompasses two main tools: `crop-images.py` and `xml_to_yolo.py`.", href: "https://github.com/karelseaat/dataset_alter_tools" },
  { repo: "feeds-and-speeds-calculator", title: "Feeds and Speeds Calculator", iconClass: "devicon-laravel-original card-icon", description: "This is a web-based application designed to help machinists and CNC programmers determine the optimal spindle speed (RPM) and feed rate for their cutting operations. The application supports both I...", href: "https://github.com/karelseaat/feeds-and-speeds-calculator" },
  { repo: "feedsandspeeds", title: "feedsandspeeds", iconClass: "devicon-python-plain card-icon", description: "A versatile Python script for calculating optimal feed rates and chip loads based on the number of flutes, spindle RPM, and material type. This repository hosts three essential files: `feedsandspee...", href: "https://github.com/karelseaat/feedsandspeeds" },
  { repo: "frequency-to-wavelength-calculator", title: "Frequency Converter - A Simple PHP Application for Frequency Conversion", iconClass: "devicon-php-plain card-icon", description: "This repository contains a simple PHP application designed to convert between different frequencies. The project is a self-contained solution for converting various frequency units into each other,...", href: "https://github.com/karelseaat/frequency-to-wavelength-calculator" },
  { repo: "historical-trip-data", title: "Historical Trip Data Analysis API (Laravel Lumen)", iconClass: "devicon-laravel-original card-icon", description: "Welcome to the Historical Trip Data Analysis API, a powerful tool for querying, filtering, and performing analytics on taxi trip data from the New York City Taxi & Limousine Commission (NYC TLC). T...", href: "https://github.com/karelseaat/historical-trip-data" },
  { repo: "imagegenerator", title: "imagegenerator", iconClass: "devicon-github-original card-icon", description: "Welcome to the `imagegenerator` repository, a Python-based application for compositing images with customizable backgrounds, midgrounds, and foregrounds. This tool can benefit developers working on...", href: "https://github.com/karelseaat/imagegenerator" },
  { repo: "imagesplitter", title: "1 Image splitter", iconClass: "devicon-github-original card-icon", description: "This project will spit images in a yes or not category. It is a tkinter gui app where you can choose a sourcemap (lots of images that load will take a lot of time) it is a tool to preliminary filte...", href: "https://github.com/karelseaat/imagesplitter" },
  { repo: "kalender-python", title: "Kalender-Python", iconClass: "devicon-python-plain card-icon", description: "A Python script for generating SVG calendars to print", href: "https://github.com/karelseaat/kalender-python" },
  { repo: "kink_gedraaid", title: "KINK FM Recently Played Songs", iconClass: "devicon-bash-plain card-icon", description: "This project provides a shell script to fetch and display the most recently played songs from the KINK FM radio station website ([kink.nl/gedraaid/kink](https://kink.nl/gedraaid/kink)) directly in ...", href: "https://github.com/karelseaat/kink_gedraaid" },
  { repo: "laravel_dashboard_app", title: "Analytics Dashboard", iconClass: "devicon-laravel-original card-icon", description: "A modern, headless analytics dashboard API built with Laravel 12 and Vite. This application provides a RESTful API for managing analytics data and metrics without frontend Blade templates.", href: "https://github.com/karelseaat/laravel_dashboard_app" },
  { repo: "lenscorrect", title: "LensCorrect Repository", iconClass: "devicon-python-plain card-icon", description: "Welcome to the LensCorrect repository, a Python-based application that corrects lens distortions in photographs of a checkerboard pattern. This tool utilizes OpenCV for image processing and Beautif...", href: "https://github.com/karelseaat/lenscorrect" },
  { repo: "macropad_macros", title: "macropad_macros", iconClass: "devicon-python-plain card-icon", description: "Welcome to the macropad_macros GitHub repository! This project contains a collection of customizable hotkey configurations for the Adafruit Feather RGB670 QWERTY Macro Pad, an ultra-compact program...", href: "https://github.com/karelseaat/macropad_macros" },
  { repo: "material-pure-flask", title: "Material Dashboard Lite - Backend", iconClass: "devicon-flask-original card-icon", description: "Welcome to the backend repository for Material Dashboard Lite, a free-to-use Material Design admin template based on Google's Material Design Lite library. This project aims to provide a responsive...", href: "https://github.com/karelseaat/material-pure-flask" },
  { repo: "meshcore-simulator", title: "MeshCore Simulator", iconClass: "devicon-python-plain card-icon", description: "A fully functional Python-based simulator for the MeshCore mesh network protocol. This tool allows developers to model complex mesh topologies with clients and repeaters, visualize signal propagati...", href: "https://github.com/karelseaat/meshcore-simulator" },
  { repo: "micro-python-sketches", title: "micro-python-sketches", iconClass: "devicon-github-original card-icon", description: "Welcome to the `micro-python-sketches` repository, a collection of examples for developing custom projects using MicroPython on ESP8266-based devices. This repository includes various scripts demon...", href: "https://github.com/karelseaat/micro-python-sketches" },
  { repo: "monitoring-api", title: "Multi-Tenant SaaS API for a Monitoring Service", iconClass: "devicon-laravel-original card-icon", description: "This project is the core backend for a Software-as-a-Service (SaaS) platform where companies can monitor the uptime and performance of their websites. It's built with Lumen and designed to handle m...", href: "https://github.com/karelseaat/monitoring-api" },
  { repo: "monte-carlo-api", title: "MonteCarloSimulation Lumen Project", iconClass: "devicon-php-plain card-icon", description: "This repository contains a Lumen PHP framework project implementing a Monte Carlo Simulation service. The project is designed to provide developers with an efficient way to perform complex simulati...", href: "https://github.com/karelseaat/monte-carlo-api" },
  { repo: "movie-graph-api", title: "MovieGraph - Film Data & Analytics API", iconClass: "devicon-laravel-original card-icon", description: "This project is a Lumen-based API for exploring movies, actors, and their intricate relationships, effectively acting as a private IMDb analytics engine. It leverages public IMDb datasets to provid...", href: "https://github.com/karelseaat/movie-graph-api" },
  { repo: "mpcncindicator", title: "mpcncindicator", iconClass: "devicon-github-original card-icon", description: "This repository contains the source code for a custom indicator light system for a CNC machine, specifically designed to communicate with a Telnet server running on a separate device.", href: "https://github.com/karelseaat/mpcncindicator" },
  { repo: "mqqt-temp-sens", title: "mqqt-temp-sens", iconClass: "devicon-html5-plain card-icon", description: "A comprehensive IoT solution for temperature and humidity sensing using the MQTT protocol with a captive portal for easy configuration of network settings and MQTT credentials.", href: "https://github.com/karelseaat/mqqt-temp-sens" },
  { repo: "nim_process_manager", title: "Nim Process Manager", iconClass: "devicon-bash-plain card-icon", description: "A simple command-line tool written in Nim for starting and managing background (daemon) processes. It is specifically designed to be used by automated agents or LLMs to execute non-blocking shell c...", href: "https://github.com/karelseaat/nim_process_manager" },
  { repo: "osmtodb", title: "osmtodb - Extracting Bicycle Shops from OpenStreetMap Data and Storing in SQLite Database", iconClass: "devicon-python-plain card-icon", description: "Welcome to the `osmtodb` project, a Python application designed for extracting bicycle shops from an OpenStreetMap (OSM) map file and storing their locations in a SQLite database. This tool serves ...", href: "https://github.com/karelseaat/osmtodb" },
  { repo: "py-informer", title: "Py Informer", iconClass: "devicon-html5-plain card-icon", description: "A MicroPython-based ESP32 project for creating dynamic access points with a web-based configuration interface.", href: "https://github.com/karelseaat/py-informer" },
  { repo: "python-screen-avg", title: "Project Overview", iconClass: "devicon-python-plain card-icon", description: "This repository contains the source code for a custom network configuration and lighting control system implemented in Python for LoRaWAN devices, specifically a LoPy board. The project is divided ...", href: "https://github.com/karelseaat/python-screen-avg" },
  { repo: "resistor-color-code-calculator", title: "Resistor Color Code Calculator", iconClass: "devicon-laravel-original card-icon", description: "This Laravel application provides a tool for electronics enthusiasts and professionals to work with resistor color codes. It can calculate the resistance value from the color bands and determine th...", href: "https://github.com/karelseaat/resistor-color-code-calculator" },
  { repo: "roadlength", title: "roadlength", iconClass: "devicon-python-plain card-icon", description: "This repository contains a Python script (`testit.py`) designed to calculate the total length of roads within a specified boundary using OpenStreetMap data.", href: "https://github.com/karelseaat/roadlength" },
  { repo: "service_discover", title: "service_discover GitHub Repository", iconClass: "devicon-python-plain card-icon", description: "Welcome to `service_discover`, a simple UDP-based client-server discovery system in Python. This project is designed for developers seeking an easy way to discover available services on a network.", href: "https://github.com/karelseaat/service_discover" },
  { repo: "sitechecker", title: "sitechecker GitHub Repository", iconClass: "devicon-python-plain card-icon", description: "This repository hosts a Python script named `sitechecker` designed to evaluate the functionality and structure of web pages for the domains `six-dots.app` and `trade.six-dots.app`. The project empl...", href: "https://github.com/karelseaat/sitechecker" },
  { repo: "tradearate", title: "1 Trade A Rate", iconClass: "devicon-flask-original card-icon", description: "A project that lets you trade a rating for one of your android apps with somebody else that also wants a android app rated. Add you app in this web tool or pick an other trading that is pending. Wh...", href: "https://github.com/karelseaat/tradearate" },
  { repo: "trello_mutator", title: "Trello Mutator", iconClass: "devicon-python-plain card-icon", description: "This repository contains a Python command-line tool designed to enhance the management of your Trello boards by integrating with the Trello API, the Ollama API, and providing intelligent suggestion...", href: "https://github.com/karelseaat/trello_mutator" },
  { repo: "trellocopy", title: "1 trellocopy", iconClass: "devicon-python-plain card-icon", description: "A python service (linux only for now) that allows you to copy to a trello list and to paste from a trello list. With only 2 shortcuts (Crtl+Alt+c and Ctrl+Alt+v) First Crtl+Alt+c and input the name...", href: "https://github.com/karelseaat/trellocopy" },
  { repo: "wekkel", title: "Wekkel - Alarm Clock and Smart Device Framework for MicroPython", iconClass: "devicon-python-plain card-icon", description: "Wekkel is an incomplete project that aims to create a smart alarm clock with additional features such as weather, stock prices, and local temperature display on a microcontroller using Micropython....", href: "https://github.com/karelseaat/wekkel" }
];

window.PORTFOLIO_GROUPS = [
  {
    slug: "arc",
    title: "Arc",
    blurb: "A quiet slice of work.",
    repos: ["Meshtastic-Simulator", "apipython", "camsimulator", "collectplayemails", "dataset_alter_tools", "feedsandspeeds", "imagegenerator", "imagesplitter", "kalender-python", "lenscorrect", "material-pure-flask", "meshcore-simulator", "osmtodb", "roadlength", "service_discover", "sitechecker", "trello_mutator", "trellocopy"]
  },
  {
    slug: "veil",
    title: "Veil",
    blurb: "Another angle through the same archive.",
    repos: ["api-app", "feeds-and-speeds-calculator", "frequency-to-wavelength-calculator", "historical-trip-data", "laravel_dashboard_app", "monitoring-api", "monte-carlo-api", "movie-graph-api", "resistor-color-code-calculator"]
  },
  {
    slug: "drift",
    title: "Drift",
    blurb: "A different pass over the same set.",
    repos: ["androidtosvg", "macropad_macros", "micro-python-sketches", "mpcncindicator", "mqqt-temp-sens", "py-informer", "python-screen-avg", "wekkel"]
  },
  {
    slug: "hollow",
    title: "Hollow",
    blurb: "The remaining fragments live here.",
    repos: ["datapanic", "kink_gedraaid", "nim_process_manager", "tradearate"]
  }
];
